## Test Models

### TODO:
* ```SIMULATE``` should return a column array (add ```transpose()```)

### Troll Metamodel

In [8]:
from TrollMetamodel import *
import numpy as np

X = np.tile(9., [10,5])
for [i,j] in [[0,0],[0,2],[1,3],[3,4],[4,4],[5,1]]:
    X[i][j] = float('nan')

test = TrollMetamodel(X,'standard')

# print(test.simulate([1,2,3]))

# print(test.estimate(1,2))

# print(np.where(np.isnan(test.data)))

troll.infer()

print(test.data)

Data check has not been implemented yet
Typespec check has not been implemented yet
[[ nan   9.  nan   9.   9.]
 [  9.   9.   9.  nan   9.]
 [  9.   9.   9.   9.   9.]
 [  9.   9.   9.   9.  nan]
 [  9.   9.   9.   9.  nan]
 [  9.  nan   9.   9.   9.]
 [  9.   9.   9.   9.   9.]
 [  9.   9.   9.   9.   9.]
 [  9.   9.   9.   9.   9.]
 [  9.   9.   9.   9.   9.]]


### NIGNormal Metamodel

In [1]:
from NIGNormalMetamodel import *

X = np.tile(9., [10,5])
for [i,j] in [[0,0],[0,2],[1,3],[3,4],[4,4],[5,1]]:
    X[i][j] = float('nan')

test = NIGNormalMetamodel(X,'standard')

print(test.simulate([1,2,3],numpredictions=10))

test.infer()
print(test.data)

print(test.estimate(1,2))

Data check has not been implemented yet
Typespec check has not been implemented yet
Constraints check was not implemented yet
([1, 2, 3], array([ 18.50065219,  14.5224099 ,  14.59332526,   1.22018276,
        22.28059207,   5.61929848,  11.65699404,  14.20268386,
        15.56119482,  17.97298759,  11.99462143,   7.35933945,
        13.75253965,   8.27211374,  14.5922155 ,  11.23446555,
        14.62231656,   6.2154243 ,   5.45792429,  -2.57768484,
        19.61396684,   7.20008221,  -1.16928855,  -6.59732333,
        -7.45381294,  19.58319561,  23.97769178,   7.38503964,
        12.53269912,   8.8670207 ]))
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
[[ 8.1  9.   8.1  9.   9. ]
 [ 9.   9.   9.   8.1  9. ]
 [ 9.   9.   9.   9.   9. ]
 [ 9.   9.   9.   9.   8. ]
 [ 9.   

### Constrained NIGNormal Metamodel

In [1]:
from ConstrainedNIGNormalMetamodel import *

X = np.tile(9., [10,5])
for [i,j] in [[0,0],[0,2],[1,3],[3,4],[4,4],[5,1]]:
    X[i][j] = float('nan')

test = ConstrainedNIGNormalMetamodel(X,'standard', bounds=[0,8])

print(test.simulate([1,2,3],numpredictions=100))

test.infer()
print(test.data)

print(test.estimate(1,2))

Data check has not been implemented yet
Typespec check has not been implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
[[ 8.  9.  8.  9.  9.]
 [ 9.  9.  9.  8.  9.]
 [ 9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  8.]
 [ 9.  9.  9.  9.  8.]
 [ 9.  8.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.]]
Data check has not been implemented yet
Typespec check has not been implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
Single Column check was not implemented yet
[[ 8.  9.  8.  9.  9.]
 [ 9.  9.  9.  8.  9.]
 [ 9.  9.  9.  9.  9.]
 [ 9

ERROR: No traceback has been produced, nothing to debug.


### Categorical Metamodel

In [ ]:
%debug
#Test basic functionalities

from CategoricalMetamodel import *

X = np.tile(1., [10,5])
for [i,j] in [[0,0],[0,2],[1,3],[3,4],[4,4],[5,1]]:
    X[i][j] = float('nan')

test = CategoricalMetamodel(X,'standard')

print(test.simulate([1,2,3],numpredictions=100))

# test.infer()
# print(test.data)

# print(test.estimate(1,2))

> <ipython-input-1-d2d7939d22ef>(2)<module>()
      1 noCols = 10
----> 2 m = [0.0 for _ in np.arange(noCols)]
      3 V = a = b = [1.0 for _ in np.arange(noCols)]

ipdb> m
*** NameError: name 'm' is not defined
ipdb> noCols
10
ipdb> np.arange(noCols)
*** NameError: name 'np' is not defined
ipdb> import numpy as np
ipdb> m = [0.0 for _ in np.arange(noCols)]
ipdb> m
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [1]:
noCols = 10
m = [0.0 for _ in np.arange(noCols)]
V = a = b = [1.0 for _ in np.arange(noCols)]
D= dict(loc=m, V=V, shape=a, scale=b)
len(D['loc'])

NameError: name 'np' is not defined

In [2]:
import scipy.stats as stats
stats.t.rvs(2,loc=1,scale=2,size=1)

array([ 3.24218087])